'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { Search, X, Menu, ArrowUp, ArrowRight, MessageCircle } from 'lucide-react';
const links=[['Work','/work'],['About','/studio'],['Services','/services'],['Process','/process'],['Contact','/contact']] as const;
export type SearchItem={title:string;href:string;description:string;category:string};
export function Header({items=[]}:{items?:SearchItem[]}) {
 const pathname=usePathname().replace(/\/$/,'')||'/',router=useRouter();
 const [compact,setCompact]=useState(false),[mode,setMode]=useState<'menu'|'search'|null>(null),[query,setQuery]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),menuButton=useRef<HTMLButtonElement>(null),searchButton=useRef<HTMLButtonElement>(null),previousMode=useRef<'menu'|'search'>('menu');
 const dark=pathname.startsWith('/work')||pathname==='/contact';
 const results=query.trim()?items.filter(item=>(item.title+' '+item.description+' '+item.category).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).slice(0,12):[];
 useEffect(()=>{const update=()=>setCompact(scrollY>40);update();addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update);},[]);
 useEffect(()=>{setMode(null);setQuery('');},[pathname]);
 useEffect(()=>{if(mode){previousMode.current=mode;dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[mode]);
 const restoreFocus=()=>{setMode(null);(previousMode.current==='menu'?menuButton:searchButton).current?.focus();};
 function searchKey(event:React.KeyboardEvent<HTMLInputElement>){if(event.key==='ArrowDown'){event.preventDefault();dialog.current?.querySelector<HTMLAnchorElement>('.search-results a')?.focus();}if(event.key==='Enter'&&results[0]){event.preventDefault();router.push(results[0].href);setMode(null);}}
 return <><a href="#main" className="skip-link">본문으로 바로가기</a><header className={`header-space ${dark?'dark-header':''} ${compact?'header-is-compact':''}`}><div className={`site-header ${compact?'is-compact':''}`}>
 <Link href="/" className="brand-logo" aria-label="OSMU STUDIO 홈"><img src="/logo.svg" alt="OSMU STUDIO" width="242" height="33"/></Link><nav className="desktop-nav" aria-label="주요 메뉴">{links.map(([label,href])=><Link key={href} href={href} aria-current={pathname===href||pathname.startsWith(href+'/')?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><button ref={menuButton} className="menu-toggle" onClick={()=>setMode('menu')} aria-label="메뉴 열기" aria-expanded={mode==='menu'} aria-controls="navigation-dialog"><Menu size={20}/></button><button ref={searchButton} className="search-toggle" onClick={()=>{setQuery('');setMode('search');}} aria-label="검색 열기" aria-expanded={mode==='search'} aria-controls="navigation-dialog"><Search size={19}/></button></div>
 </div></header><dialog ref={dialog} id="navigation-dialog" className={`navigation-dialog ${mode==='search'?'search-dialog':'menu-dialog'} ${dark?'dialog-dark':''}`} onCancel={()=>setMode(null)} onClose={restoreFocus} onClick={e=>{if(e.target===dialog.current){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setMode(null);}}} aria-label={mode==='search'?'사이트 검색':'주요 메뉴'}>
 {mode==='search'?<><div className="search-input-row"><label className="sr-only" htmlFor="site-search">프로젝트와 서비스 검색</label><input id="site-search" autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={searchKey} placeholder="Search..." autoComplete="off"/><button aria-label="검색 닫기" onClick={()=>setMode(null)}><X size={22}/></button></div><div className="search-results" aria-live="polite">{results.map(item=><Link key={item.href} href={item.href} onClick={()=>setMode(null)}><span>{item.title}</span><small>{item.category}</small><ArrowRight size={25}/></Link>)}{query.trim()&&!results.length&&<p className="search-empty">검색 결과가 없습니다.<small>프로젝트 이름이나 ‘패키지’, ‘브랜드’로 검색해 보세요.</small></p>}</div><div className="search-meta"><p>© 2026 OSMU STUDIO</p><div><a href="https://www.instagram.com/studio_osmu/" target="_blank" rel="noreferrer">Instagram</a><a href="https://pf.kakao.com/_rJrGX/chat" target="_blank" rel="noreferrer">KakaoTalk</a><a href="mailto:osmu_studio@naver.com">Email</a></div></div></>:<><div className="mobile-menu-top"><Link href="/" onClick={()=>setMode(null)} className="brand-logo"><img src="/logo.svg" alt="OSMU STUDIO" width="242" height="33"/></Link><button onClick={()=>setMode(null)} aria-label="메뉴 닫기"><X size={22}/></button><button onClick={()=>{setQuery('');setMode('search');}} aria-label="메뉴에서 검색 열기"><Search size={20}/></button></div><nav aria-label="모바일 메뉴">{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setMode(null)} aria-current={pathname===href||pathname.startsWith(href+'/')?'page':undefined}>{label}</Link>)}</nav></>}
 </dialog></>;
}
export function Footer(){
 const footer=useRef<HTMLElement>(null),logo=useRef<HTMLImageElement>(null);
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!footer.current||!logo.current)return;const r=footer.current.getBoundingClientRect();const progress=Math.max(0,Math.min(1,(innerHeight-r.top)/(r.height*.8)));logo.current.style.transform=reduced.matches?'none':`translateY(${(1-progress)*160}px)`;});};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',update);removeEventListener('resize',update);};},[]);
 return <footer ref={footer} className="footer"><div className="footer-top"><div className="footer-business"><p>© 2026 OSMU STUDIO</p><p>오스무 스튜디오 · 대표 김시우<br/>사업자등록번호 836-65-00790</p></div><div className="footer-contact"><p>Talk to us or ask us anything.</p><Link href="/contact"><ArrowRight/>Contact us</Link><Link href="/privacy"><ArrowRight/>Privacy policy</Link><Link href="/terms"><ArrowRight/>Terms of use</Link></div><div className="footer-social"><a href="https://www.instagram.com/studio_osmu/" target="_blank" rel="noopener noreferrer"><ArrowRight/>Instagram</a><a href="https://pf.kakao.com/_rJrGX/chat" target="_blank" rel="noopener noreferrer"><ArrowRight/>KakaoTalk</a><a href="mailto:osmu_studio@naver.com"><ArrowRight/>Email</a><Link href="/work"><ArrowRight/>All work</Link></div><button className="back-to-top" onClick={()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp size={38}/><span>Back to top</span></button></div><Link href="/" className="footer-wordmark" aria-label="OSMU STUDIO 홈"><img ref={logo} src="/logo.svg" alt="OSMU STUDIO" width="242" height="33"/></Link></footer>;
}

export function KakaoQuickLink(){
 return <a className="kakao-quick" href="https://pf.kakao.com/_rJrGX/chat" target="_blank" rel="noopener noreferrer" aria-label="카카오톡으로 상담하기" title="카카오톡 상담"><MessageCircle size={25} strokeWidth={2.3}/><span className="sr-only">카카오톡으로 상담하기</span></a>;
}
