export const services = [
 {slug:'branding',number:'01',title:'Brand Audit & Consulting',koreanTitle:'브랜드 진단 · 컨설팅',korean:'브랜드의 현재를 읽고, 다음 선택의 기준을 세웁니다.',rowCopy:'지금의 브랜드를 읽고, 다음 선택을 위한 기준을 함께 찾습니다.',intro:'브랜드의 방향과 우선순위를 정하기 전에, 현재 위치를 먼저 확인해야 할 때.',description:'브랜드가 놓인 시장과 고객의 선택 기준을 살펴봅니다. 흩어진 정보를 하나의 판단 기준으로 정리해, 다음 단계의 디자인과 실행이 같은 방향을 보도록 돕습니다.',outputs:['브랜드 현황 진단','고객·경쟁 환경 분석','포지셔닝 방향','핵심 가치·메시지','실행 우선순위']},
 {slug:'ci-bi',number:'02',title:'Branding',koreanTitle:'브랜딩',korean:'브랜드가 기억되는 이름과 표정을 만듭니다.',rowCopy:'이름과 언어, 시각 체계를 하나의 브랜드 경험으로 설계합니다.',intro:'브랜드의 성격을 말과 시각 언어로 분명하게 보여줘야 할 때.',description:'브랜드의 이름, 말투, 로고와 시각 요소가 하나의 인상으로 이어지도록 설계합니다. 사용할 때마다 흔들리지 않는 기준을 만들고, 필요한 응용까지 연결합니다.',outputs:['브랜드 네이밍','로고·워드마크','컬러·타이포그래피','브랜드 그래픽 시스템','가이드라인']},
 {slug:'space-branding',number:'03',title:'Graphic Design',koreanTitle:'그래픽 디자인',korean:'브랜드의 인상을 여러 매체에 구체화합니다.',rowCopy:'인쇄물부터 패키지·공간 그래픽까지, 브랜드의 인상을 구체화합니다.',intro:'브랜드의 생각을 인쇄물, 패키지와 공간의 실제 결과물로 옮겨야 할 때.',description:'정보의 우선순위와 제작 환경을 함께 살피며 그래픽을 설계합니다. 손에 쥐는 인쇄물부터 공간에서 만나는 안내까지, 매체마다 같은 인상이 이어지도록 만듭니다.',outputs:['패키지·라벨 디자인','편집·인쇄물 디자인','공간 그래픽 콘셉트','사인·웨이파인딩','현장 적용 가이드']},
 {slug:'brand-film',number:'04',title:'Photo & Film',koreanTitle:'사진 · 영상',korean:'브랜드가 움직이는 순간을 기록하고 편집합니다.',rowCopy:'사진과 영상으로 브랜드가 움직이는 순간의 리듬을 만듭니다.',intro:'브랜드의 분위기와 제품의 장면을 사진과 영상으로 전해야 할 때.',description:'브랜드의 시각 언어를 바탕으로 촬영의 장면과 편집의 리듬을 정리합니다. 제품, 공간, 사람의 모습을 채널별 쓰임에 맞는 사진과 영상 콘텐츠로 완성합니다.',outputs:['브랜드·제품 촬영','영상 기획·촬영','편집·색보정','모션그래픽','릴스·숏폼 콘텐츠']},
 {slug:'marketing',number:'05',title:'Marketing',koreanTitle:'마케팅',korean:'고객을 만나는 메시지와 채널을 연결합니다.',rowCopy:'고객을 만나는 채널과 메시지를 연결해 실행의 밀도를 높입니다.',intro:'브랜드가 준비한 이야기를 고객에게 닿는 방식으로 풀어야 할 때.',description:'론칭의 목표와 채널의 역할을 정리한 뒤, 메시지와 콘텐츠의 흐름을 설계합니다. 캠페인에 필요한 시각물과 운영 기준을 연결해 다음 실행을 준비합니다.',outputs:['마케팅 방향 설정','캠페인 메시지','SNS 콘텐츠 기획','프로모션 소재','성과 점검·개선 제안']},
 {slug:'web-digital',number:'06',title:'Web & Digital',koreanTitle:'웹 · 디지털',korean:'브랜드를 이해하고 행동으로 이어지는 화면을 만듭니다.',rowCopy:'정보가 읽히고 문의로 이어지는 디지털 접점을 설계합니다.',intro:'브랜드 소개부터 문의까지, 디지털 경험을 하나의 흐름으로 연결해야 할 때.',description:'방문자가 필요한 정보를 자연스럽게 읽고 다음 행동으로 이어지도록 정보 구조와 화면을 설계합니다. 모바일과 데스크톱 환경에서 브랜드의 인상이 유지되도록 구현합니다.',outputs:['웹사이트 정보 구조','UI·반응형 디자인','홈페이지 개발','콘텐츠 운영 구조','문의 전환 흐름']},
 {slug:'ai-image-film',number:'07',title:'AI Image & Film',koreanTitle:'AI 이미지 · 영상',korean:'AI로 브랜드의 장면을 더 빠르게 확장합니다.',rowCopy:'AI 이미지와 영상으로 촬영만으로는 만들기 어려운 장면을 설계합니다.',intro:'브랜드의 세계관을 더 넓은 장면과 움직임으로 보여줘야 할 때.',description:'생성형 AI를 스케치 도구가 아닌 제작 도구로 다룹니다. 제품과 브랜드 기준을 먼저 정리한 뒤, 원하는 장면을 설계하고 편집합니다. 실제 촬영물과 결합해 캠페인과 디지털 채널까지 일관된 콘텐츠를 만듭니다.',outputs:['AI 이미지 아트디렉션','AI 영상 콘셉트·제작','제품·공간 비주얼 확장','합성·리터칭·후반 편집','캠페인·SNS 콘텐츠']}
];
export function getService(slug:string){const aliases:Record<string,string>={'brand-identity':'ci-bi',packaging:'space-branding','space-design':'space-branding'};return services.find(s=>s.slug===(aliases[slug]||slug));}
