export const services = [
 {slug:'branding',number:'01',title:'Brand Strategy',korean:'디자인을 시작할 기준을 세웁니다.',intro:'누구에게, 어떤 이유로 선택받을지 정해야 할 때.',description:'브랜드의 현재 상황과 목표, 고객의 선택 기준을 살펴봅니다. 확인한 근거를 바탕으로 포지셔닝과 핵심 메시지를 정리하고, 이후 디자인을 판단할 기준으로 연결합니다.',outputs:['브랜드·시장 리서치','고객·경쟁 환경 분석','브랜드 포지셔닝','핵심 가치·메시지','네이밍·슬로건'],image:'creative-collaboration'},
 {slug:'ci-bi',number:'02',title:'Identity & Packaging',korean:'브랜드를 알아보는 표정을 만듭니다.',intro:'로고에서 제품 패키지까지, 일관된 인상이 필요할 때.',description:'글자, 색상과 그래픽의 관계를 설계해 브랜드의 시각 언어를 만듭니다. 제품 규격과 표기 정보, 소재와 인쇄 조건을 함께 검토하며 패키지에 적용합니다.',outputs:['로고·워드마크','컬러·타이포그래피','브랜드 그래픽 시스템','패키지·라벨 디자인','인쇄 데이터·가이드라인'],image:'package-system'},
 {slug:'space-branding',number:'03',title:'Space Graphics',korean:'공간에서 만나는 브랜드를 정리합니다.',intro:'매장과 현장의 안내, 그래픽에 브랜드 기준이 필요할 때.',description:'방문자가 공간을 발견하고 이동하며 마주치는 시각 정보를 정리합니다. 기존 공간과 시공 조건을 확인해 사인, 메뉴, 안내물과 환경 그래픽을 디자인합니다.',outputs:['공간 그래픽 콘셉트','사인·웨이파인딩','메뉴·안내물','윈도·월 그래픽','현장 적용 가이드'],image:'space-experience'},
 {slug:'brand-film',number:'04',title:'Motion & Content',korean:'정지된 인상을 움직이는 언어로.',intro:'브랜드의 리듬을 짧은 영상과 콘텐츠로 전하고 싶을 때.',description:'기존 브랜드 자산을 바탕으로 움직임의 속도와 전환 방식을 설계합니다. 채널별 화면 비율과 재생 환경을 고려해 로고 모션과 그래픽 콘텐츠를 제작합니다.',outputs:['로고 애니메이션','모션그래픽','콘텐츠 스토리보드','릴스·숏폼 그래픽','채널별 영상 포맷'],image:'brand-film'},
 {slug:'web-digital',number:'05',title:'Web & Digital',korean:'브랜드를 이해하고 행동할 수 있는 화면.',intro:'소개와 작업, 문의를 한곳에 연결해야 할 때.',description:'방문자가 알아야 할 정보의 순서를 정하고, 브랜드에 맞는 화면을 디자인합니다. 모바일과 데스크톱에서 내용을 읽고 필요한 행동으로 이어갈 수 있도록 구현합니다.',outputs:['사이트 정보 구조','UI·반응형 디자인','홈페이지 개발','포트폴리오·콘텐츠 구성','프로젝트 문의 흐름'],image:'identity-system'},
 {slug:'marketing',number:'06',title:'Launch & Campaign',korean:'준비한 브랜드를 고객 앞에 놓습니다.',intro:'제품 출시와 캠페인에 필요한 메시지·이미지를 준비할 때.',description:'출시 목표와 판매 채널에 맞춰 전달할 내용을 정리합니다. 키 비주얼을 중심으로 상세페이지, SNS와 프로모션 소재를 연결하고, 합의한 지표를 바탕으로 개선 방향을 검토합니다.',outputs:['론칭·캠페인 메시지','키 비주얼','제품 상세페이지','SNS·프로모션 소재','콘텐츠 개선 방향'],image:'brand-activation'}
];
export function getService(slug:string){const aliases:Record<string,string>={'brand-identity':'ci-bi',packaging:'ci-bi','space-design':'space-branding'};return services.find(s=>s.slug===(aliases[slug]||slug));}
